/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IZKSmartHealthCards,
  IZKSmartHealthCardsInterface,
} from "../IZKSmartHealthCards";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "immunizationId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "depth",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "zeroValue",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "adminAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "vaccineType",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "vaccineCodeSystem",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "vaccineCodeCode",
        type: "string",
      },
    ],
    name: "ImmunizationCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "relayerAddress",
        type: "address",
      },
    ],
    name: "RelayerAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "relayerAddress",
        type: "address",
      },
    ],
    name: "RelayerRemoved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "contractAddress",
            type: "address",
          },
          {
            internalType: "uint8",
            name: "merkleTreeDepth",
            type: "uint8",
          },
        ],
        indexed: false,
        internalType: "struct IZKSmartHealthCards.Verifier",
        name: "verifier",
        type: "tuple",
      },
    ],
    name: "VerifierAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "contractAddress",
            type: "address",
          },
          {
            internalType: "uint8",
            name: "merkleTreeDepth",
            type: "uint8",
          },
        ],
        indexed: false,
        internalType: "struct IZKSmartHealthCards.Verifier",
        name: "verifier",
        type: "tuple",
      },
    ],
    name: "VerifierRemoved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "operator",
        type: "address",
      },
    ],
    name: "Withdraw",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_immunizationId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_identityCommitment",
        type: "uint256",
      },
    ],
    name: "addMember",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_relayer",
        type: "address",
      },
    ],
    name: "addRelayer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_immunizationId",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "_depth",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "_zeroValue",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "_vaccineType",
        type: "string",
      },
      {
        internalType: "string",
        name: "_vaccineCodeSystem",
        type: "string",
      },
      {
        internalType: "string",
        name: "_vaccineCodeCode",
        type: "string",
      },
    ],
    name: "createImmunization",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_immunizationId",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "_vaccineCodeSystem",
        type: "string",
      },
      {
        internalType: "string",
        name: "_vaccineCodeCode",
        type: "string",
      },
    ],
    name: "isEligible",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_immunizationId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_identityCommitment",
        type: "uint256",
      },
      {
        internalType: "uint256[]",
        name: "_proofSiblings",
        type: "uint256[]",
      },
      {
        internalType: "uint8[]",
        name: "_proofPathIndices",
        type: "uint8[]",
      },
    ],
    name: "removeMember",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_relayer",
        type: "address",
      },
    ],
    name: "removeRelayer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_immunizationId",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "_signal",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "_nullifierHash",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_externalNullifier",
        type: "uint256",
      },
      {
        internalType: "uint256[8]",
        name: "_proof",
        type: "uint256[8]",
      },
    ],
    name: "verifyMembership",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IZKSmartHealthCards__factory {
  static readonly abi = _abi;
  static createInterface(): IZKSmartHealthCardsInterface {
    return new utils.Interface(_abi) as IZKSmartHealthCardsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IZKSmartHealthCards {
    return new Contract(address, _abi, signerOrProvider) as IZKSmartHealthCards;
  }
}
